<a href="https://colab.research.google.com/github/AlexLeoShin/test_1-18.10.2025/blob/main/%D0%9C%D0%BE%D0%B4%D1%83%D0%BB%D1%8C_4_%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D1%8B_%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F_%D0%BD%D0%B0_Python_%D0%B4%D0%BB%D1%8F_%D0%B0%D0%BD%D0%B0%D0%BB%D0%B8%D0%B7%D0%B0_%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D1%85.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Практическое ДЗ, Шлюпкин А.Л., группа №1.**
#**Модуль 4. Основы программирования на Python для анализа данных.**
#**4.1 Введение в Python. Ввод и вывод данных. Типы данных. Встроенные функции**

#**1. Вывод данных**

##**Задание № 1**

Задание № 1
Напишите программу, которая выводит на экран следующий текст:
**Hello Word**

Входные данные: На вход программе ничего не
подаётся.

Выходные данные: Программа должна вывести текст в соответствии с условием задачи.

In [ ]:
print('Hello Word')

Hello Word

##**Задание №2**

**Первые измерения датчиков.** В исследовательском центре проводятся испытания шести новых датчиков температуры.

Каждый датчик выдал своё первое измерение: 4, 8, 15, 16, 23 и 42 °C

Напишите программу, которая выводит эти значения в одной строке через пробел - как если бы вы просматривали «сырые данные» перед анализом.

Входные данные: На вход программе ничего не подаётся.

Выходные данные: Программа должна вывести измеренные значения температур через пробел.

In [ ]:
print(4, 8, 15, 16, 23, 42)

4 8 15 16 23 42

##**Задание №3**

**Компания анализирует, как росло число пользователей за первую неделю после запуска сервиса**.
Каждый символ * показывает количество новых пользователей в день.
Напишите программу, которая выводит текстовую визуализацию роста пользователей за 7 дней:

Входные данные: На вход программе ничего не подается.

![изображение.png]()

Выходные данные: Программа должна вывести текстовую
визуализацию, как показано выше.

In [ ]:
print('*')
print('*', '*')
print('*', '*', '*')
print('*', '*', '*', '*')
print('*', '*', '*', '*', '*')
print(('* ') * 6)
print(('* ') * 7)

*
* *
* * *
* * * *
* * * * *
* * * * * *
* * * * * * *

##**Задание №4**

**Финансовый аналитик готовит краткий отчёт о доходах компании по кварталам.**
Напишите программу, которая выводит следующую информацию на отдельных
строках:

Отчёт о доходах

1 квартал: 1200000 руб.

2 квартал: 1350000 руб.

3 квартал: 1280000 руб.

4 квартал: 1420000 руб.

Входные данные: На вход программе ничего не подаётся.

Выходные данные: Программа должна вывести указанный текст, где каждая строка начинается с
новой строки.

In [ ]:
print('Отчёт о доходах')
print('1 квартал: 1200000 руб.')
print('2 квартал: 1350000 руб.')
print('3 квартал: 1280000 руб.')
print('4 квартал: 1420000 руб.')

Отчёт о доходах
1 квартал: 1200000 руб.
2 квартал: 1350000 руб.
3 квартал: 1280000 руб.
4 квартал: 1420000 руб.

#**2. Ввод данных**

##**2.1 Переприсваемость**

##**Задание №5**

**В аналитическом отделе компании к команде присоединился новый специалист.**

Напишите программу, которая получает на вход имя нового аналитика и выводит
персональное приветствие в формате:

Добро пожаловать в команду, <имя аналитика>!

Входные данные: На вход программе подаётся одна
строка - имя аналитика.

Влад

Выходные данные: Программа должна вывести
приветствие в указанном формате.

Добро пожаловать в команду, Влад!

In [ ]:
name = input()
print('Добро пожаловать в команду, ' + name + '!') #склеили значение аргумента и символ "!", без пробела

Влад
Добро пожаловать в команду, Влад!

##**Задание №6**

**Любимая компания**. На вход программе подаётся строка текста - название
компании.

Напишите программу, которая принимает это название и выводит сообщение в
формате:

<название компании> - лидер рынка!

Входные данные: На вход программе подаётся
название компании.

Сбер

Выходные данные: Программа должна вывести текст в
соответствии с условием задачи.

Сбер - лидер рынка!

In [ ]:
love_company = input()
print(love_company + ' - лидер рынка!')

Сбер
Сбер - лидер рынка!

##**Задание №7**

**Описание набора данных.** Вы как аналитик готовите краткое описание нового
набора данных.
На вход программе подаются три строки:

1 - название набора данных, 2 - количество строк, 3 - количество столбцов.

Выведите эти три строки в том же порядке, чтобы получился черновик описания.


Входные данные:
<название> Sales Q1

<число строк> 1000

<число столбцов> 8

Выходные данные: Программа должна вывести введённые данные в той же
последовательности, каждую на
отдельной строке.

Sales Q1

1000

8

In [ ]:
name = input()
rows = input()
columns = input()
print('название', name)
print('число строк', rows)
print('число столбцов', columns)

Sales Q1
1000
8
название Sales Q1
число строк 1000
число столбцов 8

**Описание набора данных.** Вы как аналитик готовите краткое описание нового
набора данных.
На вход программе подаются три строки:

1 - название набора данных, 2 - количество строк, 3 - количество столбцов.

Выведите эти три строки в том же порядке, чтобы получился черновик описания.


Входные данные:
<название> Sales Q1

<число строк> 1000

<число столбцов> 8

Выходные данные: Программа должна вывести введённые данные в той же
последовательности, каждую на
отдельной строке.

Sales Q1

1000

8

##**Задание №8**

**Последние три отчёта.** Вы как аналитик просматриваете названия последних трёх
отчётов, загруженных в систему.

Напишите программу, которая принимает три
строки - названия отчётов - и выводит их в обратном порядке, чтобы показать их
от самого нового к самому старому.

Входные данные:

<отчёт 1> Продажи за январь

<отчёт 2> Продажи за февраль

<отчёт 3> Продажи за март

Выходные данные: Программа должна вывести введённые строки в обратной
последовательности, каждую на отдельной строке.

Продажи за март

Продажи за февраль

Продажи за январь

In [64]:
report_1 = input()
report_2 = input()
report_3 = input()
print(report_3)
print(report_2)
print(report_1)

Продажи за январь
Продажи за февраль
Продажи за март
Продажи за март
Продажи за февраль
Продажи за январь

##**Задание №9**

**Рост продаж.** В отделе аналитики вы анализируете рост продаж по товарам.

В переменной base_price хранится базовая цена товара, а в переменной growth_percent - процент увеличения цены (например, 20
означает рост на 20%).

Вычислите новую цену с учётом роста и сохраните её в переменную new_price.

Также вычислите размер прибавки (разницу между новой и старой ценой) и сохраните её в переменную delta.

Входные данные:

base_price = 100

growth_percent = 20

Выходные данные: Программа должна вычислить:
новую цену new_price
разницу между ценами delta
и вывести результаты на экран.

new_price = 120.0

delta = 20.0

In [ ]:
base_price = input()
growth_percent = input()
new_price = float(base_price) * (1 + float(growth_percent) / 100)
delta = new_price - float(base_price)
print('new_price =', round(new_price, 1))
print('delta =', round(delta, 1))

120
20
new_price = 144.0
delta = 24.0

##**2.1 Необязательные Параметры**

##**Задание №10**

**Отчёт по регионам.** Компания собирает отчёт по регионам продаж.
Необходимо вывести названия трёх регионов в одной строке,
разделив их символами ***.


Входные данные: На вход программе ничего не
подаётся.

Выходные данные:
Северный******Центральный*** ***Южный

In [ ]:
print('Северный', 'Центральный', 'Южный', sep='***') ## Вывод с использованием sep='***'

Северный***Центральный***Южный

##**Задание №11**

**Аналитик подключается к базе данных, и программа должна вывести приветствие
с его именем в одной строке, используя параметр end.**

Напишите программу, которая получает имя аналитика через input() и выводит
сообщение в формате: Подключение установлено. Добро пожаловать, <имя
аналитика>!


Входные данные: На вход программе подаётся одна
строка - имя аналитика.

Влад

Выходные данные: Программа должна вывести
приветствие в одной строке, используя
параметр end.

Подключение установлено. Добро
пожаловать, Влад!

In [65]:
name = input()
print('Подключение установлено. Добро пожаловать, ', end='')
print(name, end='')
print('!')

Влад
Подключение установлено. Добро пожаловать, Влад!

In [66]:
name = input()
print('Подключение установлено. Добро пожаловать, ', end='')
print(name + '!')

Влад
Подключение установлено. Добро пожаловать, Влад!

##**Задание №12**

**Отчёт о продажах.** Вы аналитик и хотите красиво вывести названия трёх товаров в
отчёте.
Программа должна:
1. считать разделитель, который будет использоваться между товарами. В
случае разделителем является вертикальная черта: |
2. считать названия трёх товаров,
3. вывести все три названия в одной строке, разделённые указанным
символом/строкой.


Входные данные:

строка-разделитель

название товара 1

название товара 2

название товара 3

|

Молоко

Хлеб

Сыр

**Выходные данные:**
Программа должна вывести три
названия через указанный разделитель
в одной строке.

Молоко | Хлеб | Сыр

In [67]:
separator = input()
product_1 = input()
product_2 = input()
product_3 = input()
print(product_1, product_2, product_3, sep=separator)

|
Молоко
Хлеб
Сыр
Молоко|Хлеб|Сыр

#**3. Типы переменных Python**

##**3.1 Числа с плавающей точкой (float)**

##**Задание №13**

**Целая часть числа.** Аналитик получает данные, где числа записаны в виде строк с десятичной частью.

Нужно выделить только целую часть числа и сохранить её в
переменную типа int.


Входные данные: value_str = "42.7"

Выходные данные: integer_part = 42

Подсказка:
Если попробовать сразу преобразовать строку в int, произойдёт ошибка.

Поэтому сначала нужно перевести строку в число с плавающей точкой (float),
а затем - в целое число (int)

##**3.2 Встроенные функции для работы с числами**

##**Задание №14**

**Абсолютное отклонение от плана.** Необходимо вычислить, насколько фактическое число заказов отличается от планового, и сформировать текст отчёта в формате:

'Абсолютное отклонение от плана равняется <число>'.

Где на месте <число>
должно стоять значение из abs_diff.


Входные данные:

orders_yesterday = 10

plan = 20

Выходные данные:

Абсолютное отклонение от плана
равняется 10

##**Задание №15**

**Наибольшее и наименьшее.** Аналитик получает набор из пяти чисел и должен
определить среди них минимальное и максимальное значения.

Напишите программу, которая выводит на экран результаты в формате:

Наименьшее число = <наименьшее число>

Наибольшее число = <наибольшее число>


Входные данные:

На вход программе подаются 5 целых чисел, каждое - на отдельной
строке.

1

2

3

4

5

Выходные данные:
Программа должна вывести два
сообщения, как указано выше.

Наименьшее число = 1

Наибольшее число = 5

##**3.3 Строковый тип данных (str)**

##**Задание №16**

**Компания запускает новый курс по Python.** Необходимо, чтобы система
автоматически приветствовала нового пользователя, используя его имя и
фамилию.

Программа должна вывести сообщение в формате:

Привет, <имя> <фамилия>! Вы только что начали изучать Python

**Используйте конкатенацию строк**!


Входные данные:

Антон

Иванов

Выходные данные:

Привет, Антон Иванов! Вы только что
начали изучать Python

##**Задание №17**

**Напишите программу, которая выводит известную цитату Стива Джобса:**


"Каждый в этой стране должен научиться программировать, потому что это учит
думать."


Однако цитата подаётся в двух частях - через стандартный поток ввода input(),
каждая часть на отдельной строке.

Соедините их так, чтобы на экране
отобразилась полная цитата в кавычках.


Входные данные:

«Каждый в этой стране должен
научиться программировать,

потому что это учит думать.»

Выходные данные:

"Каждый в этой стране должен
научиться программировать, потому
что это учит думать."

##**3.4 Встроенные Функции для Работы со строками.** **Логический тип данных (bool)**

##**Задание №18**

**Проверка скидки.** Магазин предоставляет скидку, если сумма покупки превышает
1000 рублей. Напишите программу, которая определяет, получит ли клиент скидку.

Входные данные: Одно число - сумма покупки.

999

Выходные данные: Одно логическое значение (True или
False).

False

##**Задание №19**

**Проверка возраста пользователя.** Аналитическая система должна определить,
является ли пользователь совершеннолетним.


Входные данные: Одно целое число - возраст.

16

Выходные данные: True, если пользователю 18 лет и
больше, иначе - False.

False

##**Задание №20**

**Встреча потоков данных.** В компании два потока данных передаются навстречу друг другу с постоянными скоростями V1 и V2 мегабайт в час.
Расстояние между потоками на старте равно S мегабайт.

Формула:
𝑡 =
𝑆
/
𝑉1 + 𝑉2

Напишите программу, которая определяет, через сколько часов потоки «встретятся» (достигнут одного и того же объёма данных).


Входные данные:

объём данных между потоками (МБ)

500.0

скорость первого потока (МБ/ч) 50.0

скорость второго потока (МБ/ч) 70.0


Выходные данные:

Программа должна вывести одно число
- время встречи потоков в часах.

4.166666666666667

##**Задание №21**

**Площадь прямоугольного треугольника.**
Напишите программу, которая считывает длины двух катетов прямоугольного
треугольника и вычисляет его площадь.

Формула для площади:
𝑆 =
𝑎 ⋅ 𝑏
/
2

где a и b - длины катетов.


Входные данные:

Длина первого катета a - 443

Длина второго катета b - 390

Выходные данные: Программа должна вывести одно число
- площадь треугольника.

86385.0

##**Задание №22**

**451 градус по Фаренгейту.** У известного американского писателя Рэя Бредбери
есть роман «451 градус по Фаренгейту».

Напишите программу, которая 40 определяет, какой температуре по шкале Цельсия соответствует указанное значение по шкале Фаренгейта.

ля получения градусов по Цельсию из градусов по Фаренгейту используйте следующую формулу:

𝑡𝐶 =
5
/
9
(𝑡𝐹 − 32)
, где 𝑡𝐹 - температура в градусах по Фаренгейту.


Входные данные: На вход программе подаётся одно
действительное число - температура в градусах по шкале Фаренгейта.

450.55

Выходные данные: Программа должна вывести одно
действительное число - температуру в
градусах по шкале Цельсия.

232.5277777777778

##**Задание №23**

**В компании SerpentData сотрудники получают бонус за проделанную работу.**
Бонус рассчитывается как 1% от дневной выручки, округлённый вниз до целого
числа.
Данные о выручке поступают из внешней системы в виде строки, поэтому
аналитик должен:
1. Преобразовать строку в число;
2. Рассчитать бонус - 1% от выручки;
3. Подготовить отчёт для менеджера.


Входные данные:

revenue_str - строка с выручкой за
день 438746.78

courier_name - имя курьера

Влад

Выходные данные:

report, содержащую строку в формате: Курьер <Имя курьера> получит бонус
<Число> р.


report = 'Курьер Антон получит бонус
4387 р.'